name: Build and deploy Python app to Azure Web App - weatherAgentBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create deployment package
        run: |
          # Create a clean zip excluding unnecessary files
          zip -r release.zip . \
            -x "*.git*" \
            -x ".github/*" \
            -x ".dockerignore" \
            -x "*.pyc*" \
            -x "__pycache__/*" \
            -x "*/__pycache__/*" \
            -x "frontend/*" \
            -x "venv/*" \
            -x "*.log" \
            -x ".env*"
          
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          
      - name: Unzip artifact for deployment
        run: |
          unzip -o release.zip
          ls -la  # List files to verify
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FC21908EFFDF4AD0AD7517282E2AC2D3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_50A26D7CBE9F478E85F42E26413BF8B5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FA776D95D0B64F77B543719AF2BC255B }}
          
      - name: Wait before deployment (prevent conflicts)
        run: |
          echo "Waiting 30 seconds to prevent deployment conflicts..."
          sleep 30
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'weatherAgentBackend'
          package: '.'
          # No slot-name parameter for student subscription
          # No clean/restart parameters to avoid conflicts
          
      - name: Verify deployment
        run: |
          echo "Deployment completed!"
          echo "App URL: https://weatheragentbackend-gvhfajajesfxddfm.canadacentral-01.azurewebsites.net"
          echo "Waiting 45 seconds for app to start..."
          sleep 45
          # Try to hit the health endpoint
          curl -f https://weatheragentbackend-gvhfajajesfxddfm.canadacentral-01.azurewebsites.net/health || echo "Health check failed - app may still be starting"
