name: Build and deploy Python app to Azure Web App - WeatherAgentBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Sanity check: can app import?"

        run: python -c "from app import app; print('✅ App loaded successfully')"

      - name: Clean up cache files
        run: |
          find . -type d -name "__pycache__" -exec rm -rf {} + || true
          find . -name "*.pyc" -delete || true
          find . -name "*.pyo" -delete || true

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . \
            -x "venv/*" \
            -x "__pycache__/*" \
            -x "*.pyc" \
            -x "*.pyo" \
            -x ".git/*" \
            -x ".github/*" \
            -x "*.log" \
            -x ".env*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E85998627DF9463A91070A01B205543C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9699EC7F418E4BF0BF98121DEF71629E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_04930C0289194405AE8043E2EDD6C89B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'WeatherAgentBackend'
          slot-name: 'Production'
          package: .
          env: |
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}
            PINECONE_ENVIRONMENT=${{ secrets.PINECONE_ENVIRONMENT }}
