# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - WeatherAgentBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        
      # Clean up cache files before zipping
      - name: Clean up cache files
        run: |
          find . -type d -name "__pycache__" -exec rm -rf {} + || true
          find . -name "*.pyc" -delete || true
          find . -name "*.pyo" -delete || true
          rm -rf venv/

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment (exclude unnecessary files)
        run: |
          zip -r release.zip . \
            -x "venv/*" \
            -x "__pycache__/*" \
            -x "utils/__pycache__/*" \
            -x "*.pyc" \
            -x "*.pyo" \
            -x ".git/*" \
            -x ".github/*" \
            -x "*.log" \
            -x ".env*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E85998627DF9463A91070A01B205543C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9699EC7F418E4BF0BF98121DEF71629E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_04930C0289194405AE8043E2EDD6C89B }}

      - name: Stop Azure Web App
        run: |
          az webapp stop --name WeatherAgentBackend --resource-group $(az webapp show --name WeatherAgentBackend --query resourceGroup -o tsv)
        continue-on-error: true

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'WeatherAgentBackend'
          slot-name: 'Production'
          timeout: 600000  # 10 minutes timeout
          restart: true
          clean: true

      - name: Start Azure Web App
        run: |
          az webapp start --name WeatherAgentBackend --resource-group $(az webapp show --name WeatherAgentBackend --query resourceGroup -o tsv)
        if: always()`